import os
import re
import asyncio
import json
import xmltodict
import xml.etree.ElementTree as ET
from dotenv import load_dotenv
from autogen_agentchat.agents import AssistantAgent, UserProxyAgent
from autogen_agentchat.teams import SelectorGroupChat
from autogen_agentchat.ui import Console
from autogen_agentchat.conditions import TextMentionTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient

# === Load environment variables ===
load_dotenv()

# === Azure OpenAI Client Setup ===
model_client = OpenAIChatCompletionClient(
    base_url=os.getenv('AZURE_OPENAI_BASE_URL'),
    model=os.getenv('AZURE_OPENAI_MODEL_NAME'),
    model_info={
        "json_output": False,
        "function_calling": True,
        "vision": False,
        "structured_output": False,
        "family": "gpt-4",
    },
    api_key=os.getenv('AZURE_OPENAI_API_KEY'),
)

# === Agents ===

user_proxy = UserProxyAgent(
    name="User_proxy",
    description="This agent initiates the BPMN generation process using a meeting transcript and terminates the session after validation.You initiate the workflow by submitting the onboarding transcript. Once the BPMN 2.0 XML is validated, the session will end."
)

generator = AssistantAgent(
    name="GeneratorAgent",
    model_client=model_client,
    description="""
This agent generates valid BPMN 2.0 XML based on a meeting transcript. The output must be compatible with BPMN editors like Camunda Modeler or bpmn.io. It must be sent to ValidatorAgent for validation.
""",
    system_message="""
You are an expert BPMN 2.0 modeler.

Generate a complete and valid BPMN 2.0 XML document based on the provided meeting transcript. The XML must be fully compatible with BPMN editors like Camunda Modeler and bpmn.io.

Important Instructions:
- The root element must be <bpmn:definitions> (not just <definitions>).
- Use the following exact namespace declaration:

  <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
                    xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
                    xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
                    xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:camunda="http://camunda.org/schema/1.0/bpmn"
                    targetNamespace="http://bpmn.io/schema/bpmn">

- Use <bpmn:process>, <bpmn:startEvent>, <bpmn:task>, <bpmn:exclusiveGateway>, <bpmn:sequenceFlow>, and <bpmn:endEvent>.
- All tags must include the bpmn: prefix.
- Every element must have a unique and valid ID.
- Optionally include a <bpmndi:BPMNDiagram> for layout rendering.
- Output must be raw XML — no extra text, explanation, or markdown.
- Send the generated XML to the ValidatorAgent next.
"""
)

validator = AssistantAgent(
    name="ValidatorAgent",
    model_client=model_client,
    description="""
This agent validates the BPMN 2.0 XML generated by GeneratorAgent. If the XML is valid, it confirms and ends the session with 'TERMINATE'. If invalid, it provides feedback and sends it back to GeneratorAgent.
""",
    system_message="""
You validate BPMN 2.0 XML documents.

If the XML is valid and can be loaded into BPMN editors like bpmn.io or Camunda Modeler, reply with a success confirmation and include 'TERMINATE' to end the session.

If the XML is invalid or non-compliant, explain the issue briefly and send it back to GeneratorAgent for correction.

Do not modify the XML yourself.
"""
)

# === Selector Group Chat Setup ===

selector_prompt = """Choose the next agent to continue the task:

{roles}

Conversation so far:
{history}

Select one agent from {participants} to proceed.
"""

team = SelectorGroupChat(
    [user_proxy, generator, validator],
    model_client=model_client,
    termination_condition=TextMentionTermination("TERMINATE"),
    selector_prompt=selector_prompt,
    allow_repeated_speaker=True,
)

# === Transcript to Trigger Generation ===

transcript = """
Meeting Transcript:
HR: After hiring is confirmed, I initiate the onboarding process by sending a welcome email and scheduling the orientation session. I also upload the employee details to the HRMS system.

HR: If the employee is a remote hire, I notify IT to ship the laptop and accessories to their address. Otherwise, I request IT to prepare the workstation in the office.

IT: Once I receive the notification, I create system credentials, assign email, and configure access rights. In parallel, I prepare the required hardware.

Compliance: I verify whether the employee has completed all mandatory background checks. If not, I flag it to HR for follow-up. If everything is cleared, I upload the verification status to the HRMS.

HR: I cross-check the compliance report. If any check is pending after 3 days, I escalate the issue to the compliance head.

Manager: Once IT and compliance tasks are completed, I receive a system alert. Then, I assign a team buddy, add the employee to the department communication groups, and share the 30-60-90 day goals.

Learning & Development (L&D): After the orientation date is confirmed, I enroll the employee in the mandatory training modules and assign a learning path based on their role.

HR: After the first week, I trigger a feedback form to the new employee and their manager to ensure onboarding satisfaction.

---

Generate a **complete and valid BPMN 2.0 XML** representation of this onboarding process.

Requirements:
- Use <bpmn:definitions> as the root tag with the proper BPMN 2.0 and Camunda namespaces.
- Include elements like <bpmn:startEvent>, <bpmn:task>, <bpmn:sequenceFlow>, <bpmn:exclusiveGateway>, <bpmn:endEvent>.
- Use unique IDs for each element.
- Include a <bpmndi:BPMNDiagram> for layout rendering if possible.
- Output only raw XML — no explanations or formatting.
"""

# === Launch the Conversation ===

async def main_async( product_flow_json):
    Response = await Console(team.run_stream(task=product_flow_json))
    print("response : ******************************\n", Response)
    print("\nresponse : ******************************")

    try :
        # Step 1: Get 2nd last message content
        second_last_message = Response.messages[-2]
        content = second_last_message.content
        content = content.replace("```xml", "").replace("```", "").strip()
        return content
        
    except Exception as e :
        print("Error accessing second last message:", e)
        return None

# result = (asyncio.run(main_async()))
# print("response : ******************************\n", result)
# print("\nresponse : ******************************")